In [1]:
import pandas as pd 
import numpy as np 

df = pd.read_csv("testdata.csv", sep="\t")
df.shape

(813, 5)

In [2]:
df.head()

        id  DSS  day    bwc    vwr
0  SvBi029    1    0  100.0   79.3
1  SvBi029    1    1  103.5  125.4
2  SvBi029    1    2  102.6   95.8
3  SvBi029    1    3  100.9   57.1
4  SvBi029    1    4  101.3   69.7

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 813 entries, 0 to 812
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      813 non-null    object
 1   DSS     813 non-null    int64
 2   day     813 non-null    int64
 3   bwc     813 non-null    float64
 4   vwr     813 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 31.9+ KB

In [4]:
active_animals = df.groupby(['day', 'DSS'])['id'].nunique().unstack(level='DSS')

print("Anzahl der aktiven Tiere im Zeitverlauf:")
display(active_animals)

survival_rate = active_animals.div(active_animals.loc[0]) * 100
print("\nÜberlebensrate (in %) relativ zum Starttag 0:")
display(survival_rate.round(1))

Anzahl der aktiven Tiere im Zeitverlauf:

DSS   0   1   2
day
0    23  22  17
1    23  22  17
2    23  22  17
3    23  22  17
4    23  22  17
5    23  22  17
6    23  21  17
7    23  21  15
8    23  19  14
9    23  18  12
10   23  18  12
11   23  18  12
12   23  18  12
13   23  18  12

Überlebensrate (in %) relativ zum Starttag 0:

DSS      0      1      2
day
0    100.0  100.0  100.0
1    100.0  100.0  100.0
2    100.0  100.0  100.0
3    100.0  100.0  100.0
4    100.0  100.0  100.0
5    100.0  100.0  100.0
6    100.0   95.5  100.0
7    100.0   95.5   88.2
8    100.0   86.4   82.4
9    100.0   81.8   70.6
10   100.0   81.8   70.6
11   100.0   81.8   70.6
12   100.0   81.8   70.6
13   100.0   81.8   70.6